/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codemonPkg4_JFurlone_A4_codemonGui */

#ifndef _Included_codemonPkg4_JFurlone_A4_codemonGui
#define _Included_codemonPkg4_JFurlone_A4_codemonGui
#ifdef __cplusplus
extern "C" {
#endif
#undef codemonPkg4_JFurlone_A4_codemonGui_FOCUS_TRAVERSABLE_UNKNOWN
#define codemonPkg4_JFurlone_A4_codemonGui_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef codemonPkg4_JFurlone_A4_codemonGui_FOCUS_TRAVERSABLE_DEFAULT
#define codemonPkg4_JFurlone_A4_codemonGui_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef codemonPkg4_JFurlone_A4_codemonGui_FOCUS_TRAVERSABLE_SET
#define codemonPkg4_JFurlone_A4_codemonGui_FOCUS_TRAVERSABLE_SET 2L
#undef codemonPkg4_JFurlone_A4_codemonGui_TOP_ALIGNMENT
#define codemonPkg4_JFurlone_A4_codemonGui_TOP_ALIGNMENT 0.0f
#undef codemonPkg4_JFurlone_A4_codemonGui_CENTER_ALIGNMENT
#define codemonPkg4_JFurlone_A4_codemonGui_CENTER_ALIGNMENT 0.5f
#undef codemonPkg4_JFurlone_A4_codemonGui_BOTTOM_ALIGNMENT
#define codemonPkg4_JFurlone_A4_codemonGui_BOTTOM_ALIGNMENT 1.0f
#undef codemonPkg4_JFurlone_A4_codemonGui_LEFT_ALIGNMENT
#define codemonPkg4_JFurlone_A4_codemonGui_LEFT_ALIGNMENT 0.0f
#undef codemonPkg4_JFurlone_A4_codemonGui_RIGHT_ALIGNMENT
#define codemonPkg4_JFurlone_A4_codemonGui_RIGHT_ALIGNMENT 1.0f
#undef codemonPkg4_JFurlone_A4_codemonGui_serialVersionUID
#define codemonPkg4_JFurlone_A4_codemonGui_serialVersionUID -7644114512714619750LL
#undef codemonPkg4_JFurlone_A4_codemonGui_serialVersionUID
#define codemonPkg4_JFurlone_A4_codemonGui_serialVersionUID 4613797578919906343LL
#undef codemonPkg4_JFurlone_A4_codemonGui_INCLUDE_SELF
#define codemonPkg4_JFurlone_A4_codemonGui_INCLUDE_SELF 1L
#undef codemonPkg4_JFurlone_A4_codemonGui_SEARCH_HEAVYWEIGHTS
#define codemonPkg4_JFurlone_A4_codemonGui_SEARCH_HEAVYWEIGHTS 1L
#undef codemonPkg4_JFurlone_A4_codemonGui_OPENED
#define codemonPkg4_JFurlone_A4_codemonGui_OPENED 1L
#undef codemonPkg4_JFurlone_A4_codemonGui_serialVersionUID
#define codemonPkg4_JFurlone_A4_codemonGui_serialVersionUID 4497834738069338734LL
#undef codemonPkg4_JFurlone_A4_codemonGui_DEFAULT_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_DEFAULT_CURSOR 0L
#undef codemonPkg4_JFurlone_A4_codemonGui_CROSSHAIR_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_CROSSHAIR_CURSOR 1L
#undef codemonPkg4_JFurlone_A4_codemonGui_TEXT_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_TEXT_CURSOR 2L
#undef codemonPkg4_JFurlone_A4_codemonGui_WAIT_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_WAIT_CURSOR 3L
#undef codemonPkg4_JFurlone_A4_codemonGui_SW_RESIZE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_SW_RESIZE_CURSOR 4L
#undef codemonPkg4_JFurlone_A4_codemonGui_SE_RESIZE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_SE_RESIZE_CURSOR 5L
#undef codemonPkg4_JFurlone_A4_codemonGui_NW_RESIZE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_NW_RESIZE_CURSOR 6L
#undef codemonPkg4_JFurlone_A4_codemonGui_NE_RESIZE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_NE_RESIZE_CURSOR 7L
#undef codemonPkg4_JFurlone_A4_codemonGui_N_RESIZE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_N_RESIZE_CURSOR 8L
#undef codemonPkg4_JFurlone_A4_codemonGui_S_RESIZE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_S_RESIZE_CURSOR 9L
#undef codemonPkg4_JFurlone_A4_codemonGui_W_RESIZE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_W_RESIZE_CURSOR 10L
#undef codemonPkg4_JFurlone_A4_codemonGui_E_RESIZE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_E_RESIZE_CURSOR 11L
#undef codemonPkg4_JFurlone_A4_codemonGui_HAND_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_HAND_CURSOR 12L
#undef codemonPkg4_JFurlone_A4_codemonGui_MOVE_CURSOR
#define codemonPkg4_JFurlone_A4_codemonGui_MOVE_CURSOR 13L
#undef codemonPkg4_JFurlone_A4_codemonGui_NORMAL
#define codemonPkg4_JFurlone_A4_codemonGui_NORMAL 0L
#undef codemonPkg4_JFurlone_A4_codemonGui_ICONIFIED
#define codemonPkg4_JFurlone_A4_codemonGui_ICONIFIED 1L
#undef codemonPkg4_JFurlone_A4_codemonGui_MAXIMIZED_HORIZ
#define codemonPkg4_JFurlone_A4_codemonGui_MAXIMIZED_HORIZ 2L
#undef codemonPkg4_JFurlone_A4_codemonGui_MAXIMIZED_VERT
#define codemonPkg4_JFurlone_A4_codemonGui_MAXIMIZED_VERT 4L
#undef codemonPkg4_JFurlone_A4_codemonGui_MAXIMIZED_BOTH
#define codemonPkg4_JFurlone_A4_codemonGui_MAXIMIZED_BOTH 6L
#undef codemonPkg4_JFurlone_A4_codemonGui_serialVersionUID
#define codemonPkg4_JFurlone_A4_codemonGui_serialVersionUID 2673458971256075116LL
#undef codemonPkg4_JFurlone_A4_codemonGui_EXIT_ON_CLOSE
#define codemonPkg4_JFurlone_A4_codemonGui_EXIT_ON_CLOSE 3L
/*
 * Class:     codemonPkg4_JFurlone_A4_codemonGui
 * Method:    JavaCompileFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_codemonPkg4_JFurlone_A4_codemonGui_JavaCompileFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     codemonPkg4_JFurlone_A4_codemonGui
 * Method:    JavaLexxYaccCompile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_codemonPkg4_JFurlone_A4_codemonGui_JavaLexxYaccCompile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     codemonPkg4_JFurlone_A4_codemonGui
 * Method:    JavaTestCodemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_codemonPkg4_JFurlone_A4_codemonGui_JavaTestCodemon
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     codemonPkg4_JFurlone_A4_codemonGui
 * Method:    JavaSelfCodemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_codemonPkg4_JFurlone_A4_codemonGui_JavaSelfCodemon
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     codemonPkg4_JFurlone_A4_codemonGui
 * Method:    JavaRunPvp
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_codemonPkg4_JFurlone_A4_codemonGui_JavaRunPvp
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     codemonPkg4_JFurlone_A4_codemonGui
 * Method:    JavaGetReport
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_codemonPkg4_JFurlone_A4_codemonGui_JavaGetReport
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
